name: Build and Publish Containers to GHCR

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - "backend/**"
      - "VERSION"
      - ".github/workflows/publish-containers.yml"

jobs:
  build-and-push:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME_FRONTEND: ${{ toLower(github.repository) }}/frontend
      IMAGE_NAME_BACKEND: ${{ toLower(github.repository) }}/backend
      VERSION: ${{ github.sha }}  # fallback, overwritten below

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set version from VERSION file
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate release notes
        id: changelog
        run: |
          echo "### Changelog" > changelog.md
          git log -n 10 --pretty=format:"- %s (%h)" >> changelog.md

      - name: Build and push frontend container
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME_FRONTEND }}:${{ steps.version.outputs.version }}
            ghcr.io/${{ env.IMAGE_NAME_FRONTEND }}:latest

      - name: Build and push backend container
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME_BACKEND }}:${{ steps.version.outputs.version }}
            ghcr.io/${{ env.IMAGE_NAME_BACKEND }}:latest

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
