name: Release
on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'specify the release version in the semver format v[major].[minor].[patch] e.g. v0.0.0'
        required: true

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    name: Build Release
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME_FRONTEND: ${{ github.repository }}/frontend
      IMAGE_NAME_BACKEND: ${{ github.repository }}/backend
      VERSION: ${{ github.sha }} 
      GITHUB_TOKEN: ${{ secrets.GH_PIPELINE_PAT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set version from VERSION file
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Convert repository name to lowercase
        id: lowercase
        run: |
          echo "repo_name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate release notes
        id: changelog
        run: |
          echo "### Changelog" > changelog.md
          git log -n 10 --pretty=format:"- %s (%h)" >> changelog.md
          
      - name: Build and push frontend container
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.repo_name }}/frontend:${{ steps.version.outputs.version }}
            ghcr.io/${{ steps.lowercase.outputs.repo_name }}/frontend:latest
            
      - name: Build and push backend container
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.repo_name }}/backend:${{ steps.version.outputs.version }}
            ghcr.io/${{ steps.lowercase.outputs.repo_name }}/backend:latest
            
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}