name: Release
on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'Specify release version in semver format (vX.Y.Z)'
        required: true

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PIPELINE_PAT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Verify GitHub token authentication
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GH_PIPELINE_PAT }}" https://api.github.com/user)
          echo "$response" | grep login || (echo "Authentication failed" && exit 1)

      - name: Set version from input
        id: version
        run: echo "version=${{ github.event.inputs.nextVersion }}" >> $GITHUB_OUTPUT

      - name: Convert repository name to lowercase
        id: lowercase
        run: echo "repo_name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PIPELINE_PAT }}

      - name: Generate release notes
        run: |
          echo "### Changelog" > changelog.md
          git log -n 10 --pretty=format:"- %s (%h)" >> changelog.md

      - name: Build and push frontend container
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.repo_name }}/frontend:${{ steps.version.outputs.version }}
            ghcr.io/${{ steps.lowercase.outputs.repo_name }}/frontend:latest

      - name: Build and push backend container
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.repo_name }}/backend:${{ steps.version.outputs.version }}
            ghcr.io/${{ steps.lowercase.outputs.repo_name }}/backend:latest

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PIPELINE_PAT }}
